
platform :ios, '11.0'
inhibit_all_warnings!

target 'Example' do
  use_frameworks!
  
  # @strongify @weakify
  pod 'libextobjc'
  pod 'Masonry'
  pod 'LXMRow', :path => '../'
  
  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
           end
      end
    end
  end
end
